# Étape de construction
FROM node:23-alpine as builder
WORKDIR /app

# Installer les dépendances
COPY App/package.json App/package-lock.json ./
RUN npm install

# Copier le code source de l'application
COPY App ./

# Construire l'application Angular
RUN npm run build --prod

# Étape de production avec Nginx
FROM nginx:alpine
COPY --from=builder /app/dist/app/browser /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
